### ISSUE TITLE
PR job without GITHUB_PULL_REQUEST_NUMBER set

### ISSUE THREAD

**Issue by juliorenner** [SAP/InfraBox#387]
**Describe the bug**
My PR jobs do not have the GITHUB_PULL_REQUEST_NUMBER environment variable configured. We have the branches and the PR webhooks enabled and it seems that it is the issue. I would expect that as it is a PR its hook would be chosen instead of the branch hook.

**To Reproduce**
1. Enable the branches and PR hooks in the GitHub repository configurations.
2. Check a job triggered by a PR, the PR information is not provided.

**Expected behavior**
I would expect that the information related to the PR would be injected in the jobs, as for example, the GITHUB_PULL_REQUEST_NUMBER.

**Screenshots**
![Screen Shot 2020-02-22 at 12 16 23](https://user-images.githubusercontent.com/10155271/75094834-7f137800-556d-11ea-9d27-cf7e01dcdcd9.png)

**Desktop (please complete the following information):**
 - OS: OSx
 - Browser: chrome
 - Version 80.0.3987.106

**Additional context**

**Comment by meranos** [comment]
Hi Julio,
since InfraBox only processes `Pushes` and `Pull requests`, the additional `Branches` trigger shouldn't cause any issues.
However, your project most likely also has the `Pushes` hook activated and GitHub sends this event before the corresponding `Branches` event. This causes a build to be created based on the push event, therefore not having any of the PR metadata.
While this behavior isn't ideal, an simple workaround should be just disabling the `Pushes` hook.

Best,
Karsten
